version: "3"
services:
    daphne:
        build: ./daphne
        container_name: daphne
        env_file:
            - ".env"
        volumes:
            - ./daphne:${APP_ROOT}
            - static:$STATIC_ROOT
            - media:$MEDIA_ROOT
        links:
            - database
        #restart: always
    database:
        image: postgres
        env_file:
            - ".env"
        #restart: always
    redis:
        image: redis
        ports:
        - "6379:6379"
        #restart: always
    nginx:
        image: nginx
        env_file:
            - ".env"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
            - static:$STATIC_ROOT
            - media:$MEDIA_ROOT
        links:
            - daphne
        ports:
            - "80:80"
        #restart: always
volumes:
    static:
        driver: local
    media:
        driver: local